In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("/home/ayushhh/CUTM/SEM1/DAVP/IRIS.csv")

In [2]:
# copy() use to create a copy of the data in separate dataframe
df_clean = df.copy()

In [ ]:
df_clean.shape #check no of row and column
df_clean.columns #list columns
df_clean.dtypes #check datatype
df_clean.info #inspect all
df.describe

<bound method DataFrame.info of       Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 6 columns]>

In [ ]:
# handling missing values
df_clean.isnull() #check if missing data is present
df_clean.isnull().sum() #Count missing values in each column

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [11]:
#created a missing data for demo
df_missing = df_clean.copy()

df_missing.loc[0, "SepalLengthCm"] = np.nan
df_missing.loc[5, "PetalWidthCm"] = np.nan
df_missing.loc[10, "Species"] = np.nan

df_missing.head(12)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            NaN           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           NaN  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2          NaN
11  12            4.8           3.4            1.6           0.2  Iris-setosa

In [13]:
df_missing.isnull().sum()

Id               0
SepalLengthCm    1
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     1
Species          1
dtype: int64

In [19]:
# dropna() Remove rows containing missing values
df_no_missing = df_missing.dropna()
df_missing.dropna()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [20]:
df_missing.dropna(subset=["Species"]) #Remove rows only when a specific column is missing
df_missing.dropna(axis=1) #Remove columns containing missing values (0: rows and 1:column)

      Id  SepalWidthCm  PetalLengthCm
0      1           3.5            1.4
1      2           3.0            1.4
2      3           3.2            1.3
3      4           3.1            1.5
4      5           3.6            1.4
..   ...           ...            ...
145  146           3.0            5.2
146  147           2.5            5.0
147  148           3.0            5.2
148  149           3.4            5.4
149  150           3.0            5.1

[150 rows x 3 columns]

In [ ]:
# Fill missing values